name: Automated Builds
on: [push]
jobs:
  win32-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Win32 Build
        shell: powershell
        run: ./win32_build.ps1 -Package -Tagged -Installer
      - name: Archive Win32 Package
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            GIPS-*.exe
            GIPS-*.zip
  linux-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Prerequisites
        run: |
          sudo apt -y update
          sudo apt -y install rpm ninja-build libgl-dev libwayland-dev libx11-dev libxrandr-dev libxinerama-dev libxkbcommon-dev libxcursor-dev libxi-dev
      - name: Linux Build
        run: make package
      - name: Archive Linux Packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            gips*.deb
            gips*.rpm
            gips*.tar.xz
